# bluemarble
# vim: ts=4 expandtab
name: ci-build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: compile
      shell: bash
      run: make

    - name: archive lc
      uses: actions/upload-artifact@v3
      with:
        name: lc-${{github.run_number}}
        path: | 
          lc
